package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"gopkg.in/yaml.v2"
)

func genconfig(clustername string, cadata string, serverurl string, namespace string, saname string, token string) string {
	fmt.Println("Creating kubeconfig file...")
	// A strucure to hold output kubeconfig yaml data
	type Cluster struct {
		CertificateAuthority string `json:"certificate-authority-data"`
		Server               string `json:"server"`
	}
	type Clusters struct {
		Cluster Cluster `json:"cluster"`
		Name    string  `json:"name"`
	}
	type Context struct {
		Cluster   string `json:"cluster"`
		Namespace string `json:"namespace"`
		User      string `json:"user"`
	}
	type Contexts struct {
		Context Context `json:"context"`
		Name    string  `json:"name"`
	}
	type User struct {
		Token string `json:"token"`
	}
	type Users struct {
		Name string `json:"name"`
		User User   `json:"user"`
	}

	type AutoGenerated struct {
		CurrentContext string     `json:"current-context"`
		APIVersion     string     `json:"apiVersion"`
		Clusters       []Clusters `json:"clusters"`
		Contexts       []Contexts `json:"contexts"`
		Kind           string     `json:"kind"`
		Users          []Users    `jspn: "users"`
	}
	ag := new(AutoGenerated)
	ag.APIVersion = "v1"
	ag.Kind = "Config"
	ag.CurrentContext = clustername
	ag.Clusters = make([]Clusters, 0)
	cs := Cluster{CertificateAuthority: cadata,
		Server: serverurl,
	}
	css := Clusters{Name: clustername, Cluster: cs}
	ag.Clusters = append(ag.Clusters, css)
	ag.Contexts = make([]Contexts, 0)
	ct := Context{Cluster: clustername,
		Namespace: namespace,
		User:      saname}
	cts := Contexts{
		Context: ct,
		Name:    clustername}
	ag.Contexts = append(ag.Contexts, cts)
	ag.Users = make([]Users, 0)
	usr := User{Token: token}
	usrs := Users{Name: saname, User: usr}
	ag.Users = append(ag.Users, usrs)
	d, err := yaml.Marshal(&ag)
	if err != nil {
		log.Fatalf("yaml.Marshal failed with '%s'\n", err)
	}
	filename := `output.yaml`
	var strconfig string
	strconfig = string(d)
	err = ioutil.WriteFile(filename, []byte(strconfig), 0644)
	if err != nil {
		log.Fatalf("writing kubeconfig faile failed '%s'\n", err)
	}
	fmt.Println("created kubeconfig file called output.yaml in present working directory ✓")
	return strconfig
}
